### ISSUE TITLE
Small Improvement

### ISSUE THREAD

**Issue by Trolleybus** [JuergenGutsch/angular2-aspnetcore#3]
Very nice, thank you a lot for the this wonderful template. While playing around with your code I came across a small improvement, which could be worthwhile considering. In the  "scripts" => "prepublish" in  project.json the webpack can be added.

FROM
`"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min"]`
TO
`"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min", "webpack" ]`

But besides that nicely done!

**Comment by JuergenGutsch** [comment]
Thanks, for the issue :) Why did you close that? You also could create a PR
